fix: Getting Started at README.md
microsoft/windows-drivers-rs pull request #213
Opened 2024-09-06 02:06 UTC by aphage

2024-09-06 03:11 UTC, wmmc88 commented on README.md
> +      driver: &mut DRIVER_OBJECT,
`DRIVER_OBJECT` is not available in UMDF

See the note on line 139: 
> Note: In Kernel Mode crates, you can use driver: &mut DRIVER_OBJECT instead of driver: PDRIVER_OBJECT.

2024-09-06 03:12 UTC, wmmc88 requested changes
Nice catch on `configure_wdk_binary_build`. please see comment for other change

2024-09-06 06:13 UTC, aphage commented on README.md
> +      driver: &mut DRIVER_OBJECT,
OK.

2024-09-06 22:32 UTC, wmmc88 approved these changes
thanks for the docs fix @aphage !

2024-09-09 01:56 UTC, aphage commented
> thanks for the docs fix @aphage !

You're welcome.

2024-09-23 21:31 UTC, hamzamust approved these changes

2024-09-23 21:34 UTC, ayodejiige approved these changes

2024-09-23 23:31 UTC, merged